### ISSUE TITLE
Error in I2C::send

### ISSUE THREAD

**Issue by deadprogram** [Bluebie/littlewire.rb#4]
The line https://github.com/Bluebie/littlewire.rb/blob/master/lib/i2c.rb#L33 has an error, in that the param `end_with_stop` is a boolean, but the expected value is an integer ala https://github.com/Bluebie/littlewire.rb/blob/master/lib/i2c.rb#L22

**Comment by Bluebie** [comment]
Could you fix it or tell me exactly what to change? I don't have any i2c devices, so the i2c part of the library is totally untested...

**Comment by deadprogram** [comment]
Something like this:

``` ruby
  def write send_buffer, end_with_stop = false
    send_buffer = send_buffer.pack('c*') if send_buffer.is_a? Array
    raise "Send buffer is too long" if send_buffer.length > 7

    # TODO: Send multiple requests to handle send buffers longer than 7 bytes
    @wire.control_transfer(
      bRequest: 0xE0 | send_buffer.length | ((end_with_stop ? 1 : 0) << 3),
      wValue: (send_buffer.bytes[1] << 8) + send_buffer.bytes[0],
      wIndex: (send_buffer.bytes[3] << 8) + send_buffer.bytes[2]
    )
  end
```

It still does not seem to work for my needs, due to the message length probably?

**Comment by deadprogram** [comment]
My comment "It still does not seem to work for my needs, due to the message length probably?" refers to the Wii nunchuck in issue #5

**Comment by kehribar** [comment]
Hi,

Littlewire can send maximum 4 I2C messages with a single USB command. Therefore if you want to send 7 messages at once, you should set END_WITH_STOP variable false at your first command, but set at the second one. 

You can see a C based implementation of I2C example here: https://github.com/littlewire/Little-Wire/blob/master/software/examples/i2c_blinkM.c

In this example I always set END_WITH_STOP since I wasn't exceeding 4 byte limit at once.

Also In this example, you can see that I can send 1 byte or 3 bytes of messages. You don't have to always send 4 messages at once.

Best,
ihsan.

**Comment by Bluebie** [comment]
This issue was never a thing, afaict. So I close it
